ravi-singh-100/DSA-Hacktober2022

Java Program/README
Java Program/Recursion With Array/LinearSearch.java

I have added recursion program in java and also updated readme file please check and merge with relevant tags. Thanks !

Added recursion program in Java and readme updated

---

Cpp program/nth_fibonaci_number.cpp
Cpp program/pascal_triangle.cpp

Added the code for pascal triangle and nth Fibonacci  number in CPP

Added code in Cpp language pascal triangle

---

Leetcode/42. Trapping Rain Water.cpp

Sir, I solved LeetCode problem no. 42 Trapping Rian Water.

added LeetCode problem no. 42 solution.

---

Leetcode/60. Permutation Sequence.cpp

Sir, I solved LeetCode question no. 60 Permutation Sequence.

added LeetCode question no. 60 solution

---

Leetcode/2124. Check if All A's Appears Before All B's.cpp

Given a string s consisting of only the characters 'a' and 'b', return true if every 'a' appears before every 'b' in the string. Otherwise, return false.
Example 1:
Input: s = "aaabbb"
Output: true
Explanation:
The 'a's are at indices 0, 1, and 2, while the 'b's are at indices 3, 4, and 5. Hence, every 'a' appears before every 'b' and we return true.
Example 2:
Input: s = "abab"
Output: false
Explanation:
There is an 'a' at index 2 and a 'b' at index 1.
Hence, not every 'a' appears before every 'b' and we return false.
Example 3:
Input: s = "bbb"
Output: true
Explanation:
There are no 'a's, hence, every 'a' appears before every 'b' and we return true.

Create 2124. Check if All A's Appears Before All B's.cpp

---

Leetcode/1512. Number of Good Pairs

Given an array of integers nums, return the number of good pairs.
A pair (i, j) is called good if nums[i] == nums[j] and i < j.
Example 1:
Input: nums = [1,2,3,1,1,3]
Output: 4
Explanation: There are 4 good pairs (0,3), (0,4), (3,4), (2,5) 0-indexed.
Example 2:
Input: nums = [1,1,1,1]
Output: 6
Explanation: Each pair in the array are good.
Example 3:
Input: nums = [1,2,3]
Output: 0

Create 1512. Number of Good Pairs

---

Leetcode/2119. A Number After a Double Reversal.cpp

Reversing an integer means to reverse all its digits.
For example, reversing 2021 gives 1202. Reversing 12300 gives 321 as the leading zeros are not retained. Given an integer num, reverse num to get reversed1, then reverse reversed1 to get reversed2. Return true if reversed2 equals num. Otherwise return false.
Example 1:
Input: num = 526
Output: true
Explanation: Reverse num to get 625, then reverse 625 to get 526, which equals num.
Example 2:
Input: num = 1800
Output: false
Explanation: Reverse num to get 81, then reverse 81 to get 18, which does not equal num.
Example 3:
Input: num = 0
Output: true
Explanation: Reverse num to get 0, then reverse 0 to get 0, which equals num.

Create 2119. A Number After a Double Reversal.cpp

---

C Program/Lift.c
C Program/Wending Machine.c
Cpp program/Bubble Sort Visualised.cpp
Cpp program/Selection Sort Visualised.cpp

Added some programs which I feel would be helpful for community and to which they can look and try. Will add a fun challenge for people learning C and C++ and looking for new ideas. Happy Hactober and Happy coding!!

Added some C and C++ Programs

---

C Program/Mergesort_C.c

Added Merge_sort_C.c

---

C Program/Linked_list_all_operations_in_all.c
C Program/Reverse the linked list.c

Merge this code asap. accordingly i will add all files for doubly , cricular linked list, then also stack , tree part.thanks

This two files include all the operations for Singly linkedlist

---

Cpp program/deleting middle in stack.cpp

i added a problem in c++ can you please merge it.

added stack problem in c++

---

C Program/RadixSort.c

Hacktoberfest-2022 Added Radix Sort

---

Cpp program/Tower_Of_Hanoi.cpp

I have created tower of hanoi problem's solution

Created tower of hanoi 

---

Leetcode/4sum-ii.py

Added the code for leetcode problem with solution in Python

Created 4sum-ii.py

---

Leetcode/groupAnagrams.cpp

Created groupAnagrams.cpp

---

Java Program/Reverse Integer.java

Given a signed 32-bit integer x, return x with its digits reversed. If reversing x causes the value to go outside the signed 32-bit integer range.

Create Reverse Integer.java

---

Cpp program/palindrome.cpp

palindrome code added

---

Python Program/SieveOfEratosthenes.py

Respected sir! please merge it.

added new algorithm in python(SieveOfEratosthenes)

---

Leetcode/1512. Number of Good Pairs.cpp

Create 1512. Number of Good Pairs.cpp

---

Leetcode/412. Fizz Buzz.cpp

Create 412. Fizz Buzz.cpp
